name: Deploy Static HTML to AWS S3

on:
  push:
    branches:
      - master  # Change to 'main' if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Deploy to S3 using AWS CLI
      - name: Sync files to S3
        run: |
          # If your site is built (e.g., React/Vue), replace ./ with your build folder (e.g., ./dist)
          aws s3 sync ./ s3://automationcicd/ --delete
